package haxby.db.pdb;
public class PDBMineral {
	public final static String[][] mineral  = {
		{ "ALLA", "ALLANITE" },
		{ "ALT", "ALTERATION PRODUCT" },
		{ "AMPH", "AMPHIBOLE" },
		{ "ANAL", "ANALCITE" },
		{ "APA", "APATITE" },
		{ "BIO", "BIOTITE" },
		{ "CALC", "CALCITE" },
		{ "CARB", "CARBONATE" },
		{ "CATS", "CaAl(AlSiO6)" },
		{ "CCR", "CaCr(AlSiO6)" }, 		//10
		{ "CHROM", "CHROMITE" },
		{ "CLY", "CLAY MINERAL" },
		{ "CPX", "CLINOPYROXENE" },
		{ "CRIS", "CRISTOBALITE" },
		{ "CTI", "CaTi(Al2O6)" },
		{ "EP", "EPIDOTE" },
		{ "FE-OX", "FE-OXIDE" },
		{ "FSP", "FELDSPAR" },
		{ "GAR", "GARNET" },
		{ "GM", "GROUNDMASS" },			//20
		{ "GM-GL", "GLASSY GROUNDMASS" },
		{ "GONN", "GONNARDITE" },
		{ "ILM", "ILMENITE" },
		{ "JD", "NaAl(Si2O6)" },
		{ "KF", "FELDSPAR" },
		{ "MICA", "MICA" },
		{ "MT", "MAGNETITE" },
		{ "NAC", "NaCr(Si2O6)" },
		{ "NATR", "NATROLITE" },
		{ "OL", "OLIVINE" },			//30
		{ "OPQ", "OPAQUE MINERAL" },
		{ "OPX", "ORTHOPYROXENE" },
		{ "PHIL", "PHILIPPSITE" },
		{ "PHLOG", "PHLOGOPITE" },
		{ "PLAG", "PLAGIOCLASE" },
		{ "PREH", "PREHNITE" },
		{ "PY", "PYRITE" },
		{ "QZ", "QUARZ" },
		{ "SAP", "SAPONITE" },
		{ "SCAP", "SCAPOLITE" },		//40
		{ "SERP", "SERPENTINE" },
		{ "SLFA", "SULFATE" },
		{ "SLFI", "SULFIDE" },
		{ "SMEC", "SMECTITE" },
		{ "SODA", "SODALITE" },
		{ "SP", "SPINEL" },
		{ "SPH", "SPHENE" },
		{ "TI-MT", "TI-MAGNETITE" },
		{ "TRI", "TRIDYMITE" },
		{ "VES", "VESICLES" },			//50
		{ "VES-F", "FILLED VESICLE" },
		{ "ZEOL", "ZEOLITE" },
		{ "ZIRC", "ZIRCON" },
		{ "AB", "ALBITE" },
		{ "AUG", "AUG" },
		{ "CHL", "CHL" },
		{ "CHLOR", "CHLOR" },
		{ "CHR", "CHROMITE" },
		{ "GL", "GLASS" },
		{ "HYGR", "HYGR" },				//60
		{ "INT", "INT" },
		{ "IO", "IO" },
		{ "OX", "OX" },
		{ "PUMP", "PUMP" },
		{ "RUT", "RUT" },
		{ "SULF", "SULF" },
		{ "TIMT", "TI-MAGNETITE" },
		{ "ZEO", "ZEOLITE" },
		{ "NN", "UNKNOWN" } };
}
